### ISSUE TITLE
Help understanding iteration in differential

### ISSUE THREAD

**Issue by ryzhyk** [TimelyDataflow/differential-dataflow#189] opened 2019-07-13 20:22 UTC
I ran into a situation where iterative computation does not behave the way I expected it to.  I am fairly sure the bug is in my understanding and was hoping @frankmcsherry or someone else could help clarify it for me.

I am using the following Datalog-friendly `Variable` implementation courtesy to Frank (BTW, is there a better way to do this now?).  The relevant part is the `drop()` method at the bottom of the listing, which connects the loop after applying `threshold()` to it. I expected `threshold` to ensure that the resulting collection returned by `deref()` is distinct. But after using this implementation for a while, I ran into an example where this is not the case.  Part of my problem is that I could not find a precise mathematical specification of how loops in timely/differential compute their output.  I wonder if there is a formula I could use to predict the output of the loop?

```
/// A collection defined by multiple mutually recursive rules.
///
/// A `Variable` names a collection that may be used in mutually recursive rules. This implementation
/// is like the `Variable` defined in `iterate.rs` optimized for Datalog rules: it supports repeated
/// addition of collections, and a final `distinct` operator applied before connecting the definition.
pub struct Variable<'a, G: Scope, D: Default+Data+Hashable>
where G::Timestamp: Lattice+Ord {
    feedback: Option<Handle<Child<'a, G, Product<G::Timestamp, TSNested>>, (D, Product<G::Timestamp, TSNested>, Weight)>>,
    current: Collection<Child<'a, G, Product<G::Timestamp, TSNested>>, D>,
    cycle: Collection<Child<'a, G, Product<G::Timestamp, TSNested>>, D>,
    name: String
}

impl<'a, G: Scope, D: Default+Data+Hashable> Variable<'a, G, D> where G::Timestamp: Lattice+Ord {
    /// Creates a new `Variable` from a supplied `source` stream.
    pub fn from(source: &Collection<Child<'a, G, Product<G::Timestamp, TSNested>>, D, Weight>, name: &str) -> Variable<'a, G, D> {
        let (feedback, cycle) = source.inner.scope().loop_variable(TSNested::one());
        let cycle_col = Collection::new(cycle);
        let mut result = Variable { feedback: Some(feedback), current: cycle_col.clone().filter(|_| false), cycle: cycle_col, name: name.to_string() };
        result.add(source);
        result
    }

    /// Adds a new source of data to the `Variable`.
    pub fn add(&mut self, source: &Collection<Child<'a, G, Product<G::Timestamp,TSNested>>, D, Weight>) {
        self.current = self.current.concat(source);
    }
}

impl<'a, G: Scope, D: Default+Data+Hashable> ::std::ops::Deref for Variable<'a, G, D> where G::Timestamp: Lattice+Ord {
    type Target = Collection<Child<'a, G, Product<G::Timestamp,TSNested>>, D, Weight>;
    fn deref(&self) -> &Self::Target {
        &self.cycle
    }
}

impl<'a, G: Scope, D: Default+Data+Hashable> Drop for Variable<'a, G, D> where G::Timestamp: Lattice+Ord {
    fn drop(&mut self) {
        if let Some(feedback) = self.feedback.take() {
           self.current.threshold(|_,c| if c.is_zero() { 0 } else { 1 })
                            .inner
                            .map(|(x,t,d)| (x, Product::new(t.outer, t.inner + 1), d))
                            .connect_loop(feedback);
        }
    }
}
```

**Comment by frankmcsherry** [comment] 2019-07-13 22:26
> But after using this implementation for a while, I ran into an example where this is not the case.

Do you happen to have a repro for this, or just noticed some output glitches as a computation went along. It is indeed supposed to be the case that what comes out of `threshold` is distinct, and based on the logic above I would have thought this too.

Differential iterative computations produce their output in `leave()`, which produces the stream of all updates `(data, time, diff)` but with the iterative component of the timestamp stripped off. This means that the output is the accumulation of all the changes across the iterations, and is meant to be the "last" value of the collection (as we accumulate all changes across iterations).

In the code above, calling, `leave()` on the results of `deref()` should be essentially the same as the output of `self.current.threshold(...)`, as that appears to be what was fed back around the loop. The only discrepancy I can think of is that if `t.inner+1` would wrap around, we end up suppressing it. Nonetheless, I think the output should still be just the distinct output of the previous round.

**Comment by frankmcsherry** [comment] 2019-07-13 22:45
> BTW, is there a better way to do this now?

I think when I last looked at this, I was able to get the performance characteristics of the above code using straight differential variables, without needing timely innards. It's in a blog post somewhere, I believe (perhaps the one on doing interning?). I'll try and track it down for you.

**Comment by frankmcsherry** [comment] 2019-07-13 23:02
I suspect this code https://github.com/TimelyDataflow/differential-dataflow/blob/master/examples/graspan.rs#L81-L134 might be related to where I ended up on this. It does things in addition to maintaining distinct edges, but if you defocus your eyes and ignore those, it looks like a Datalog variable.

It is possible that this isn't as optimized as we got to in our side discussions (maintaining only .. I think twice the number of facts, is what we got to, but let's start here and I can correct this example as we patch back together how to do this.

**Comment by ryzhyk** [comment] 2019-07-13 23:18
Thanks! The behavior is reproducible, and in fact only requires a simple program and a few input records to trigger, which is surprising given that we have a bunch of tests with recursion working just fine. Problem is, this is DDlog-generated code, so not exactly the minimal failing example.  Let me send you a DDlog-generated Rust project that triggers assertion violation due to non-distinct output (in the next message) and then I will try to write a simplified version directly in differential.

**Comment by ryzhyk** [comment] 2019-07-13 23:52
`https://github.com/ryzhyk/non_distinct_iteration`

`redistributionspan.dl` is the DDlog program and `commands` is the input that triggers this.

Instructions to reproduce are in the README.

Will start working on a simplified version. Many thanks for looking into this!

**Comment by frankmcsherry** [comment] 2019-07-14 00:38
Thanks! I can confirm that this panics for me too, but I can also confirm that I have no clue what code is running! :D

Is there a synthesized `_.rs` file somewhere which would have the program that panics?

**Comment by ryzhyk** [comment] 2019-07-14 00:51
The synthesized file is `lib.rs`. But this is just a data structure that describes the dataflow graph. The interpreter for this datastructure is `differential_datalog/program.rs`, which is where the panic happens:

```
thread 'worker thread 0' panicked at 'assertion failed: x.2 == 1 || x.2 == -1', differential_datalog/program.rs:1034:41
```

Right now I am trying to replace this with a normal DD program that will hopefully be a lot easier to follow.

**Comment by ryzhyk** [comment] 2019-07-18 17:03
Hmm, I posted a follow-up message with a simplified reproducible bug 4 days ago, but only now realized that the message did not go through.  Anyhow, it is in the same repository (https://github.com/ryzhyk/non_distinct_iteration).  There is still a lot of generated code there, but it is all dead code now. Here is the relevant part that implements two simple datalog rules with recursion and aggregation:

https://github.com/ryzhyk/non_distinct_iteration/blob/57e31046c487226576706fd16a32e348be928b64/main_ddlog/differential_datalog/program.rs#L865 

The assertion triggers when a record with multiplicity -2 comes out of the iteration during the second transaction.

**Comment by frankmcsherry** [comment] 2019-07-20 00:42
Just a guess looking at the code (I can build it, but it produces a library rather than an executable):

You probably want a `consolidate()` here:

https://github.com/ryzhyk/non_distinct_iteration/blob/master/main_ddlog/differential_datalog/program.rs#L931

just before the inspect. I'm not certain that this is the problem, but it looks like you are inspecting the results of leaving the iteration, which should *logically* represent distinct elements, but which may emerge as physical updates with varying counts. The `consolidate()` operator ensures that the physical representation matches the logical representation.

I'll poke a bit more to try and turn things in to an exe, but if this is equally easy for you to test give me a shout if you learn before I do!

**Comment by ryzhyk** [comment] 2019-07-20 06:05
Yes, you are right, this was the problem, many thanks for helping out!!  I am reluctant to use `consolidate()`, as it seems to introduce an extra arrangement, but I will stop making the incorrect assumption about weights in `inspect()`.

**Comment by frankmcsherry** [comment] 2019-07-20 10:26
You are in luck! Consolidate does use arrangements, but it doesn't maintain them. There should be no additional memory footprint (it uses arrange, but drops the trace handle, which results in batch formation but not trace maintenance).

**Comment by ryzhyk** [comment] 2019-07-20 19:08
Lucky indeed, thanks for the clarification!

So, just to confirm, is it correct to expect that after `consolidate` we will only see at most one update to a record for each timestamp? And if we apply `consolidate` to a distinct collection, then the weight of the update can only be +1 or -1?

Thanks!

**Comment by frankmcsherry** [comment] 2019-07-20 20:47
That is my firm belief, yes. I'm not aware of other ways, short of bugs or a deeply flawed understanding on my part (to be honest, I don't often end up reasoning about the diff magnitudes, so this is new to me too).

**Comment by ryzhyk** [comment] 2019-07-21 20:18
Thanks! Can I ask for another clarification?

Assuming that input timestamps to the DD computaiton grow monotonically (i.e., having seen an update with timestamp `n`, we will never see an update with timestamp `<n`), do output timestamp ***for a given collection*** grow monotonically as well?  And if this is not generally guaranteed, does `consolidate` enforce such output monotonicity?

**Comment by frankmcsherry** [comment] 2019-07-22 03:03
Not exactly in order, no. The outputs come from batches, which may span several timestamps. If you them in order you may want a custom timely operator (perhaps one that uses 'delay', which does timestamp reordering internally).

Alternately, you could snag the batches themselves, which will have monotonically increasing frontiers. If you pop open consolidate you could skip the 'as_collrction' call to get the stream of batches.

**Comment by ryzhyk** [comment] 2019-07-22 06:14
Understood! No, I don't necessarily need them to be in order, but now that I know they can be reordered I will make sure my code does not implicitly assume it.

**Comment by frankmcsherry** [comment] 2019-11-18 19:12
Closing as "resolved" I believe (the conclusion being that DD doesn't proactively compact all collections, which is not messaged well; can add to the long list of documentation needs).

**Closed by frankmcsherry** 2019-11-18 19:12 UTC
