### ISSUE TITLE
The examples crash in debug mode with multiple workers

### ISSUE THREAD

**Issue by pec0ra** [TimelyDataflow/differential-dataflow#85] opened 2017-11-08 12:11 UTC
Both bfs and reachability examples crash when run with multiple workers and a number of round high enough.

## Expected Behavior
Both examples should run without crashing.

## Actual Behavior
The examples crash after a variable number of rounds with the error: 
```
thread 'worker thread 1' panicked at 'Progress error; internal "Subgraph": ((Root, 86), 1)', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/timely-0.3.0/src/progress/nested/subgraph.rs:979:28
```

## Steps to Reproduce the Problem
Run the example with:
`cargo run --example bfs -- 2 2 1 500 false -w 4`
or
`cargo run --example reachability -- 2 2 1 500 -w 4`

**Comment by frankmcsherry** [comment] 2017-11-08 12:13
Uh oh. I'll get on this.

**Comment by frankmcsherry** [comment] 2017-11-08 12:17
A quick look suggests that this may just be an issue of a spurious `debug_assert!`; the test that is failing is more aggressive than it should be. I'm going to try and fix up the test to be accurate, and see if this cleans up the error.

**Comment by frankmcsherry** [comment] 2017-11-08 15:47
After quite a lot of head scratching (!#$!# distributed systems) I think I have sorted out what the issue is. I'm going to try and explain it, and you may want to bail out with the explanation that "debug test is too stringent" and I'll push a more lax version once I figure out what it should be.

The more complicated explanation is that timely dataflow (this is down underneath differential dataflow) tracks the ability of each operator in the dataflow graph to send timestamped messages at each timestamp. It does this between multiple workers by having them announce changes in their capabilities to each other.

Because timely dataflow is "sophisticated", these exchanges aren't atomic, and you can get some weird re-orderings. The one that is tripping the `debug_assert!` seems to be:

0. There are at least two workers, managing subgraphs that consume messages and create capabilities,
1. One worker ingests a message into its subgraph, and exchanges that message over to the other worker. Having done so, it starts to send the progress update "ingested message, now inbound to operator X", but the progress update doesn't get there yet.
2. The other worker is clueless, and its subgraph finds that one of the operators it manages has (i) consumed an input message, and (ii) now holds a capability for that time. Although the subgraph has not yet seen evidence of the message ingestion into the subgraph, and so cannot report that such a thing has happened, it does express the capability.
3. Everyone loses their shit, because someone just expressed a capability without evidence that they should be allowed to do so (the "evidence" is the operators solemn promise that it did actually consume a message, but since we are still awaiting details of the existence of that message in the first place, there is no evidence to present upwards).

Now, nothing inappropriate has happened in the exchange above. No one will incorrectly believe that existing capabilities cannot exist, but there is a bit of a tangle in the accumulated message and capability count to determine who really has what data. In the second subgraph there is a negative message count, because something has been consumed that hasn't formally been known to exist yet. This could be an issue if the operators were "malicious", where we had to wait until we saw proof of a message before granting the capability. Since we know that these subtractions only come from legit messages received, because we wrote that code, we know that there is some message out there waiting for us.

**Comment by frankmcsherry** [comment] 2017-11-08 16:03
I'm going to re-file this as an issue in the timely dataflow repo, if that is ok. I suspect the immediate fix will be to comment out the test as overly pessimistic, but I have a bunch of re-commenting and stuff that I want to check in with it.

**Comment by frankmcsherry** [comment] 2017-11-08 16:55
This is now issue https://github.com/frankmcsherry/timely-dataflow/issues/107

**Comment by frankmcsherry** [comment] 2017-11-08 18:08
I believe this should be fixed by https://github.com/frankmcsherry/timely-dataflow/pull/106, at least it is fixed locally for me. It will mean that you'll need to use the github repo for timely, rather than crates.io, on account of updating crates is dangerous and requires a version bump to avoid me screwing things up. :)

**Closed** 2019-02-16 20:59 UTC
